### ISSUE TITLE
Feature request: Create a new broadcast receiver from an unsubscribed one

### ISSUE THREAD

**Issue by thombles** [abbychau/multiqueue2#3]
Hi, thanks for your work updating this crate! I tried to use it this week and ran across this design problem which makes it difficult to use.

* My broadcaster starts out with no subscribers
* It will dynamically create new Receivers over time
* Once I hand out a Receiver, I have no access to it any more

Since new Receivers are created by cloning, I need to hold one copy alongside my Sender. But if I am not draining it, the broadcast queue will not progress. However to drain it I need to move it into a tokio task which means I lose access for cloning.

To get around this I can see a few options:

1. The Sender is able to spawn new Receivers by itself (probably difficult, based on the code I read)
2. `unsubscribe()` does not consume `self`. I _think_ it contains enough information that it could create a new Receiver.
3. `unsubscribe()` does consume `self`, but it returns some sort of token that can be upgraded to a new Receiver.

Do you have any ideas how I could handle this use case?

**Comment by abbychau** [comment]
Hi. Can you post or send me a sample code that goes into this problem?

**Comment by abbychau** [comment]
`Receivers` has to do `recv.add_stream()` to be added as a "broadcast-ee"

**Comment by thombles** [comment]
Sure, I've written some sample code below. My object that is broadcasting events also retains a receiver.

It's possible that I'm misunderstanding the documentation. It shows an example with `add_stream`, which will block if there is a consumer that is not being drained. However you can also create a new receiver by cloning, as shown below. I thought that the Receiver inside EventCreator would stop the stream advancing, but it does not for some reason.

It is okay to clone the receiver like this and keep a copy? Will that have any negative effects?

```rust
use multiqueue2::{BroadcastReceiver, BroadcastSender, broadcast_queue};
use std::thread;
use std::time::Duration;

#[derive(Clone)]
struct Event;

struct EventCreator {
    sender: BroadcastSender<Event>,
    receiver: BroadcastReceiver<Event>,
}
impl EventCreator {
    fn new() -> Self {
        let (s, r) = broadcast_queue(5);
        Self {
            sender: s,
            receiver: r,
        }
    }

    fn subscriber(&self) -> BroadcastReceiver<Event> {
        // "Received an event!" is printed 8 times before it hangs
        //self.receiver.add_stream()
        // "Received an event!" is printed 100 times - the retained Receiver does not affect the clone
        self.receiver.clone()
    }

    fn generate_event(&self) {
        // In real code, use the Sink properly
        let _ = self.sender.try_send(Event);
    }
}

fn main() {
    let ec = EventCreator::new();

    // Make a subscriber
    let rx = ec.subscriber();
    let join = thread::spawn(move || {
        for _r in rx {
            println!("Received an event!");
        }
    });
        
    for _ in 0..100 {
        ec.generate_event();
        thread::sleep(Duration::from_millis(10));
    }

    // End the thread at the end of the experiment
    drop(ec);
    let _ = join.join();
}
```

**Comment by abbychau** [comment]
> It is okay to clone the receiver like this and keep a copy? Will that have any negative effects?
Yes. if A = B.clone(); , then they are stealing from the queue.
for instance, A gets 1,3,4,5,9 ; B gets 2,6,7,8,10,11,12


Here is a way to produce subscriber clones without draining.

Make the class mutable with the following function.
```Rust
    fn subscriber(&mut self) -> BroadcastReceiver<Event> {
        let r = self.receiver.add_stream();
        self.receiver=r.clone();
        r
    }
```

```Rust
use multiqueue2::{broadcast_queue, BroadcastReceiver, BroadcastSender};
use std::{thread, time::Duration};

#[derive(Clone)]
struct Event {
    i: i64,
}

struct EventCreator {
    sender: BroadcastSender<Event>,
    receiver: BroadcastReceiver<Event>,
}
impl EventCreator {
    fn new() -> Self {
        let (s, r) = broadcast_queue(5);
        Self {
            sender: s,
            receiver: r,
        }
    }

    fn subscriber(&mut self) -> BroadcastReceiver<Event> {
        let r = self.receiver.add_stream();
        self.receiver=r.clone();
        r
    }

    fn generate_event(&self, i: i64) {
        match self.sender.try_send(Event { i }) {
            Ok(_) => {}
            Err(e) => {
                println!(
                    "Try send error:{:?} : {:?}",
                    e,
                    ::std::time::SystemTime::now()
                );
            }
        }
    }
}

fn main() {
    let mut ec = EventCreator::new();
    let rx1 = ec.subscriber();
    let rx2 = ec.subscriber();
    let mut c: i64 = 1;

    let join1 = thread::spawn(move || {
        for r in rx1 {
            println!("A : {} : {:?}", r.i, ::std::time::SystemTime::now());
        }
    });
    let join2 = thread::spawn(move || {
        for r in rx2 {
            println!("B : {} : {:?}", r.i, ::std::time::SystemTime::now());
            thread::sleep(Duration::from_millis(100));
        }
    });

    for _ in 0..100 {
        c = c + 1;
        ec.generate_event(c);
        thread::sleep(Duration::from_millis(100));
    }

    // End the thread at the end of the experiment
    drop(ec);

    let _ = join1.join();
    let _ = join2.join();
}

```

**Comment by thombles** [comment]
Aha! Great example, thank you for writing it out. That works fine and I don't need my "feature" after all. I'll close the issue.
